version: "2"
services:
  mongo:
    image: mongo
    volumes:
      - ~/data:/data/db
    ports:
      - "27017:27017"
  app:
    build: ./node_server/
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - "3000:3000"
    command: >
      bash -c "./wait-for-it.sh mongo:27017 -- npm start"
