apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    run: jwt-app
  name: jwt-app
  namespace: default
  resourceVersion: "49724"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/jwt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      run: jwt-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: jwt-app
    spec:
      containers:
      - image: docker.io/vibguldev/jwt-app:latest
        imagePullPolicy: Always
        name: jwt-app
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          privileged: true
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - /opt/app/trigger.sh
          initialDelaySeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
